### ISSUE TITLE
a plugin to get lyricText that load/download by ESLyric(foo_uie_eslyric.dll)

### ISSUE THREAD

**Issue by ghost** [tomato111/Lyric-Show-Modoki#5]
ttsping add COM features to [ESLyric](https://hydrogenaud.io/index.php/topic,111278.0.html) component and that enables WSH Panel Mod (Plus) to get lyric text through a callback function which is useful if someone do not intend to use ESLyric panel but WSH-Lyric (like Lyric-Show-Modoki) to display lyrics.

ESLyric is powerful to download (and parse) lyrics and I`m glad to make use of it. here is the code:

``` javascript
pl = {
    name: 'lplugin_ESLyric',
    label: 'ESLyric: 检索',
    author: 'Elia',
    onStartUp: function() {
        var ESLyric; 

        // ESLyric component is installed and can create COM object.
        try {
            ESLyric = new ActiveXObject("ESLyric");
        } catch (e) {
            return;
        }
        //
        ESLyric.SetLyricCallback(onLyricGet);
        fb.IsPlaying && fb.RunMainMenuCommand('View/ESLyric/Reload lyric'); // trigger onLyricGet
        // fb.IsPlaying && fb.RunMainMenuCommand('视图/ESLyric/重载歌词');

        function onLyricGet(obj) {

            main(obj.lyricText);

        }

    },

    onCommand: function() {
        if (!utils.checkComponent("foo_uie_eslyric"))
            return;
        fb.IsPlaying && fb.RunMainMenuCommand('View/ESLyric/Search...');
        // fb.IsPlaying && fb.RunMainMenuCommand('视图/ESLyric/搜索歌词...');
    }
}
```

> ESLyric with COM is not released in public but it' ll not take long.

**Comment by ghost** [comment]
I do not know when but not want to pull commit 0705da3 now as a request but it happens. The plugin is not stable and has a lot to do now.

**Comment by tomato111** [comment]
thx! I'll merge a commit(2074791) for now.

**Comment by tomato111** [comment]
thx! I'll merge a commit(2074791) for now.
